services:
  - type: redis
    name: quake-redis
    plan: starter
    region: ohio
    ipAllowList: [] # only allow internal connections

  - type: web
    name: quake
    plan: standard
    runtime: docker
    region: ohio
    envVars:
      - key: APPSMITH_ENCRYPTION_SALT
        sync: false
      - key: APPSMITH_ENCRYPTION_PASSWORD
        sync: false
      - key: APPSMITH_ENABLE_EMBEDDED_DB
        value: 0
      - key: APPSMITH_SIGNUP_DISABLED
        value: true
      - key: APPSMITH_DISABLE_TELEMETRY
        value: true
      - key: APPSMITH_MONGODB_URI
        sync: false
      - key: APPSMITH_REDIS_URL
        fromService:
          type: redis
          name: quake-redis
          property: connectionString